env:
  global:
    - secure: PMjXVTYYCVRPVY54IPPvEsRbZfBwWHoUm2N6O8kCIy87JRQgp6J6WfOy1vw/DZnc8xHVJ4/G2ZBCUO5ntE36nLAbz1PI9GkhYk9t7VsvNqkQawSkY/YnvZ9Vt9QxBc3VozCCrscf+4ebMXkktffA4WbzOsdXNYSWtBVKM1KYwZc=
language: rust
after_script:
  - (curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh)
