language: rust
script:
    - cargo build --verbose
    - cargo test --verbose
    - rustdoc --test README.md -L target
    - cargo doc
after_success: |
    mv target/doc . &&
    (curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh)
env:
    global:
        - secure: PMjXVTYYCVRPVY54IPPvEsRbZfBwWHoUm2N6O8kCIy87JRQgp6J6WfOy1vw/DZnc8xHVJ4/G2ZBCUO5ntE36nLAbz1PI9GkhYk9t7VsvNqkQawSkY/YnvZ9Vt9QxBc3VozCCrscf+4ebMXkktffA4WbzOsdXNYSWtBVKM1KYwZc=
