[package]

name = "xdg-rs"
version = "0.0.1"
authors = ["skullzzz <kiran.eighty9@gmail.com>"]
license = "MIT"
repository = "https://github.com/skullzzz/xdg-rs"
keywords = ["xdg"]
readme = "README.md"
description = "Utility to library to better manage the XDG spec"

[lib]
name = "xdg"
